/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Flight.Similateur.UI;

import Flight.Similateur.Objects.RadarSocket;
import javax.swing.UIManager;

/**
 *
 * @author mfaour
 */
public class RadarFrame extends javax.swing.JFrame {

    RadarSocket _socketClient = null;

    public RadarFrame() {
        initComponents();
        this.setSize(1500, 800);
        this.setLocationRelativeTo(null);
        _socketClient = new RadarSocket(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstFlights = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jSplitPane3.setLeftComponent(jPanel2);

        lstFlights.setFont(new java.awt.Font("Monospaced", 1, 26)); // NOI18N
        lstFlights.setToolTipText("");
        lstFlights.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstFlightsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstFlights);

        jSplitPane3.setRightComponent(jScrollPane2);

        txtInfo.setEditable(false);
        txtInfo.setColumns(20);
        txtInfo.setFont(new java.awt.Font("Monospaced", 1, 26)); // NOI18N
        txtInfo.setRows(5);
        jScrollPane1.setViewportView(txtInfo);

        jSplitPane3.setLeftComponent(jScrollPane1);

        getContentPane().add(jSplitPane3, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstFlightsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstFlightsValueChanged

    }//GEN-LAST:event_lstFlightsValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (_socketClient != null) {
            _socketClient.fermer_communication();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            System.out.println("Look & Feel exception");
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane3;
    public javax.swing.JList<String> lstFlights;
    public javax.swing.JTextArea txtInfo;
    // End of variables declaration//GEN-END:variables
}
